server:
  port: 8763

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Joyin-x/ssmstart.git
          username: Joyin-x
          search-paths: config
          password: 1461483915
  application:
      name: config
